In [1]:
import numpy as np

In [3]:
a1 = np.zeros(10)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a2 = np.ones(10) * 5
print(a2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
a3 = np.arange(10, 51)
print(a3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [8]:
a4 = np.arange(0, 9).reshape(3, 3)
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
a5 = np.linspace(0, 1, num = 20)
print(a5)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
