<font size="4"><b> Python Basics and Numpy Excercise:

Data types:Numbers,Strings,Printing,Lists,Dictionaries,Tuples, Arrays and Numpy </b> </font>

<b> Q-1: What will be the output of the following expression ((15%3)**(16/2))+7  ?</b>

In [2]:
print(((15%3)**(16/2)) + 7)

7.0


<b> Q-2: Split this string: s = "Hi I am learning python!" into a list. </b>

In [3]:
s = "Hi I am learning python!"
l = s.split()
print(l)

['Hi', 'I', 'am', 'learning', 'python!']


<b> Q-3: Create a 2D array my_2darray of size 4*5 initialized with random values between 1 and 100. </b>

In [7]:
import random
rows, cols = (4, 5)
my_2darray = [[random.randrange(100) for j in range(cols)] for i in range(rows)]
print(my_2darray)

[[81, 4, 2, 21, 28], [89, 19, 94, 87, 42], [2, 64, 9, 77, 13], [50, 71, 88, 74, 25]]


<b> Q-4:Print all the elements from row 0 to 2 (both inclusive) and column 1 to 3 (both inclusive) of my_2darray. </b>


In [16]:
for i in range(3):
    for j in range(1, 4):
        print(my_2darray[i][j], end = " ")
    print()

4 2 21 
19 94 87 
64 9 77 


<b>Q-5:What is the main difference between a tuple and a list?</b>

In [5]:
Lists are mutable, but tuples are immutable.

<b> Q-6: Create a nested list with name learn_list with the following elements [[1,2,3], [[1,2,3],Get,Set,Go]] and grab the word 'Go'</b>

In [18]:
learn_list = [[1, 2, 3], [[1, 2, 3], "Get", "Set", "Go"]]
print(learn_list[1][-1])

Go


<b> Q-7:Given this nested dictionary 'd' grab the word "hello"</b>

<b>d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [19]:
d = {"k1": [1, 2, 3, {"tricky": ["oh", "man", "inception", {"target": [1, 2, 3, "hello"]}]}]}
print(d["k1"][-1]["tricky"][-1]["target"][-1])

hello


<b> Q-8:Create a function that counts the number of times the word "hello" occurs in a string. </b>

In [21]:
def word_count(str, word):
    count = 0
    for w in str.split():
        if w == word:
            count += 1
    return count

In [22]:
print(word_count("a python is programming in python", "python"))

2


<font size="3"><b> Next two questions are based on NumPy library. Import numpy before solving question 9 and 10 </b> </font>
   

<b> Q-9: Create an array of cubes of first 10 natural numbers using arange function.</b>



In [23]:
import numpy as np

In [24]:
arr = np.arange(1, 11) ** 3
print(arr)

[   1    8   27   64  125  216  343  512  729 1000]


<b> Q-10: Write code to print the following matrix  
    
 array([[ 1,  2,  3,  4,  5],<br>
       [ 6,  7,  8,  9, 10],<br>
       [11, 12, 13, 14, 15],<br>
       [16, 17, 18, 19, 20],<br>
       [21, 22, 23, 24, 25]])<br> 
       
       and grab the following segment
       
       array([[ 2], 
             [ 7],  
             [12]])


In [25]:
arr = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15],
               [16, 17, 18, 19, 20],
               [21, 22, 23, 24, 25]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
print(arr[0:3, 1].reshape(3,1))

[[ 2]
 [ 7]
 [12]]
